language: python
python:
  - 2.7
install:
  - pip install -e .
  - pip install coveralls
script:
  - coverage run --source spacegame setup.py test
after_success:
  coveralls
notifications:
  email: false
